# Generated by Django 2.0 on 2018-01-13 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('unit', models.FloatField(default=1)),
                ('work_type', models.IntegerField(choices=[(0, 'count'), (1, 'weight'), (2, 'time')])),
            ],
        ),
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.FloatField()),
                ('is_overtime', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Product')),
            ],
        ),
    ]
